apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "phpldapadmin.fullname" . }}
  labels:
    {{- include "phpldapadmin.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.env | nindent 2 }}
  