apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "phpldapadmin.fullname" . }}
  labels:
    {{- include "phpldapadmin.labels" . | nindent 4 }}
data:
  LDAPBASE: {{ cat "dc=" .Values.ldapDomain | replace "." ",dc=" | nospace | quote }}
  {{- toYaml .Values.env | nindent 2 }}
