apiVersion: v2
name: nginx-default-backend
description: A Helm chart to create a custom backend for your Nginx ingress
icon: https://docs.nginx.com/nginx-ingress-controller/images/icons/NGINX-Ingress-Controller-product-icon.svg
type: application

maintainers:
  - name: roertel
    email: roertel@users.noreply.github.com

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2-0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v20230215-helm-chart-4.5.2-3-g15ecd2531"
