apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "minecraft-overviewer.fullname" . }}
  labels:
    {{- include "minecraft-overviewer.labels" . | nindent 4 }}
data:
  config.py: |-
    {{- if .Values.config }}
      {{- print "# Values from user-specified." | nindent 4 }}
      {{- .Values.config | nindent 4 }}
      
    {{- else }}
      {{- print "# Values from default (helm) configuration." | nindent 4 }}
      {{- include "config.py" . | nindent 4 }}
    {{- end }}

    {{- if .Values.extraConfig }}
      {{- print "# Values from user-specified extra configuration." | nindent 4 }}
      {{- .Values.extraConfig | nindent 4 }}
    {{- end }}
