# Where to set concurrent policy to false?
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "minecraft-overviewer.fullname" . }}
  labels:
    {{- include "minecraft-overviewer.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.regenerationSchedule }}"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations: {{ toYaml . | nindent 12 }}
          {{- end }}
          labels: {{ include "minecraft-overviewer.selectorLabels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.renderer.repository }}:{{ .Values.image.renderer.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.renderer.pullPolicy }}
            env:
              - name: MINECRAFT_VERSION
                value: "{{ .Values.minecraftVersion }}"
              {{- range $name, $value := .Values.extraEnv }}
              - name: {{ $name }}
                value: {{ $value | quote }}
              {{- end }}
            volumeMounts:
              - name: config
                mountPath: /opt
                readOnly: true
              - name: world
                mountPath: /home/minecraft/server/
                readOnly: true
              - name: map
                mountPath: /home/minecraft/render/
                readOnly: false
              - name: home
                mountPath: /home/minecraft/.minecraft
                readOnly: false
            securityContext: {{ toYaml .Values.securityContext | nindent 14 }}
          volumes:
            - name: config
              configMap:
                name: {{ include "minecraft-overviewer.fullname" . }}
            - name: world
              {{- if .Values.world.claimName }}
              persistentVolumeClaim:
                claimName: {{ .Values.world.claimName }}
              {{- end }}
            - name: map
              {{- if .Values.map.persistent }}
              persistentVolumeClaim:
                claimName: {{ include "minecraft-overviewer.fullname" . }}
              {{- end }}
            - name: home
              emptyDir: {}
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{ toYaml . | nindent 12 }}
          {{- end }}
