apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minecraft-overviewer.fullname" . }}
  labels:
    {{- include "minecraft-overviewer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "minecraft-overviewer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "minecraft-overviewer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "minecraft-overviewer.serviceAccountName" . }}
      initContainers:  # One time setup to create index.html if the www is empty
        - name: init-{{ .Chart.Name }}
          image: busybox
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          command: ['/bin/touch', '/mnt/index.html']
          volumeMounts: [{ name: map, mountPath: /mnt }]
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.display.repository }}:{{ .Values.image.display.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.display.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: map
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: temp
              mountPath: /var/cache/nginx
            - name: temp
              mountPath: /var/run
      volumes:
        - name: map
        {{- if .Values.map.persistent }}
          persistentVolumeClaim:
            claimName: {{ include "minecraft-overviewer.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: temp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
