# Default values for mariadb-manifests.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backup: {}

connection: {}

database: {}

grants: {}

mariadb: {}

maxscale: {}

restore: {}

sqljob: {}

users: {}
