{{- if .Values.tls.enabled -}}
{{- if eq .Values.tls.type "certificate" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mariadb.fullname" . }}-tls
  labels: {{ include "mariadb.labels" . | nindent 4 }}
spec:
  secretName: {{ include "mariadb.fullname" . }}-tls
  {{- with .Values.tls.certificate }}
  commonName: {{ .commonName }}
  issuerRef: {{ toYaml .issuerRef | nindent 4 }}
  {{- with .optional }}
  {{- toYaml . | nindent 2 -}}
  {{- end -}}
  {{- end -}}
{{- end -}}
{{- end -}}
