apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels: {{ include "mariadb.labels" . | nindent 4 }}
data:
  my.cnf: |
    {{- include "my.cnf" . | nindent 4 }}
  {{- if .Values.ldap.enabled }}
  nsswitch.conf: |
    {{- include "nsswitch.conf" . | nindent 4 }}
  mariadb: |
    {{- include "pam-mariadb" . | nindent 4 }}
  ldap-init.sql: |
    {{- include "ldap-init.sql" . | nindent 4 }}
  {{ end -}}
