apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
data:
  my.cnf: |
  {{ include "my.cnf" . | nindent 4 }}
{{- if .Values.ldap.enabled }}
---
apiVersion: v1
kind: ConfigMap
  name: {{ include "mariadb.fullname" . }}-ldap
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
data:
  nslcd.conf.tpl: |
  {{ include "nslcd.conf" . | nindent 4 }}
{{- end }}