apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels: {{ include "mariadb.labels" . | nindent 4 }}
data:
  mariadb-root-password: {{ (include "mariadb.rootPassword" . ) | b64enc | quote }}
  {{- if .Values.ldap.enabled }}
  ldap-bindpw: {{ .Values.ldap.bindPw | default "password" | b64enc | quote }}
  {{- end }}
