apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels: {{ include "mariadb.labels" . | nindent 4 }}
data:
  {{- $connection_admin_password := (include "mariadb.connection-admin-password" . ) }}
  {{- $mariadb_root_password := (include "mariadb.rootPassword" . ) }}
  mariadb-root-password: {{ $mariadb_root_password | b64enc | quote }}
  {{- if .Values.ldap.enabled }}
  ldap-bindpw: {{ .Values.ldap.bindPw | default "password" | b64enc | quote }}
  {{- end }}
stringData:
  {{- if .Values.tls.enabled }}
  tls-init.sql: |
    GRANT CONNECTION ADMIN ON *.* TO 'connection_admin'@'localhost' IDENTIFIED BY {{ $connection_admin_password | squote }};
  nslcd.conf.tpl: |
    {{- include "nslcd.conf.tpl" . | nindent 4 }}
  connection-admin-my.cnf: |
    [client]
    username=connection-admin
    password={{ $connection_admin_password | quote}}
  {{- end -}}
