apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{ include "openldap.labels" . | nindent 4 }}

  name: {{ include "openldap.fullname" . }}
  
data:
  # One time init if the DB is absent. Sets up modules and access
  init.ldif: |
    {{ include "init.ldif" . | indent 4 }}
  config.ldif: |
    {{ include "config.ldif" . | indent 4 }}