apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "minecraft-overviewer.fullname" . }}
  labels:
    {{- include "minecraft-overviewer.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config.files }}
  {{ $key }}: |
    {{- $val | nindent 4 }}
  {{- end }}
