apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-default-backend.fullname" . }}-config
  labels:
    {{- include "nginx-default-backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.errorPages }}
  {{ $key }}: |- 
  {{- $value | nindent 2 }}
  {{- end }}
