# Default values for minecraft-overviewer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- (int) Number of replicas to start. It only makes sense to have 1.
replicaCount: 1

# -- (string) Minecraft version for game save file.
minecraftVersion: "1.19.3"

image:
  renderer:
    repository: "mide/minecraft-overviewer"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    # tag: "latest"
  display:
    repository: nginx
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "stable"

#      ┌────────────────── timezone (optional)
#      |      ┌───────────── minute (0 - 59)
#      |      │ ┌───────────── hour (0 - 23)
#      |      │ │ ┌───────────── day of the month (1 - 31)
#      |      │ │ │ ┌───────────── month (1 - 12)
#      |      │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
#      |      │ │ │ │ │                                   7 is also Sunday on some systems)
#      |      │ │ │ │ │
#      |      │ │ │ │ │
# CRON_TZ=UTC * * * * *
#
# Or @yearly, @annually, @monthly, @weekly, @daily, @midnight or @hourly
# -- (string) Regeneration schedule. Use a cron-compatible schedule or consider
# -- @daily, @midnight or @hourly.
regenerationSchedule: "@daily"

# -- (string) Configuration override. Replaces the default configuration file.
config:

# -- (string) Extra configuration settings to append to the default or
# -- previously-specified configuration.
extraConfig:

# -- Extra environment variables to pass to Overviewer.
# -- See https://github.com/mide/minecraft-overviewer for options.
extraEnv: {}
  # RENDER_POI: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations:
  kube-score/ignore: container-image-tag,container-image-pull-policy

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10000
  runAsGroup: 10000
  # fsGroup: 20000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: minecraft-overviewer.local
      paths:
      - path: /
        backend:
          serviceName: minecraft-overviewer.local
          servicePort: 80
  tls: []
  #  - secretName: minecraft-overviewer-tls
  #    hosts:
  #      - minecraft-overviewer.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

world: {}  # Name of volume from minecraft server
  # claimName: minecraft-data

map:  # where to store generated map
  persistent: false
  storageClassName:
  size: 1Gi
