{{- if .Capabilities.APIVersions.Has "k8s.mariadb.com/v1alpha1" }}
{{- if .Values.backups -}}
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup

metadata:
  {{- with .Values.backup.metadata }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

spec:
  mariaDbRef:
    name: {{- .Values.mariadb.metadata.name }}
  {{- with .Values.backup.spec | omit "mariaDbRef" }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
