{{- $apiversion := "k8s.mariadb.com/v1alpha1" }}
{{- $kind := "Grant" }}

{{- if .Capabilities.APIVersions.Has (printf "%s/%s" $apiversion $kind) }}
{{- $labels := include "mariadb-manifests.labels" . }}
{{- with get .Values (lower $kind) }}
apiVersion: {{ $apiversion }}
kind: {{ $kind }}
metadata:
  {{- include "mariadb-manifests.metadata" . | nindent 2 }}
  labels:
    {{- nindent 4 $labels }}
spec:
  {{- include "mariadb-manifests.spec" . | nindent 2 }}
{{- end }}
{{- end }}
