{{- $apiversion := "k8s.mariadb.com/v1alpha1" }}
{{- $kind := "MariaDB" }}
{{- if .Capabilities.APIVersions.Has (printf "%s/%s" $apiversion $kind) }}
{{- $defaults := include (printf "mariadb-manifests.%s-defaults" (lower $kind)) . | fromYaml }}
{{- with get .Values (lower $kind) }}
{{- $localvalues := merge . $defaults }}
apiVersion: {{ $apiversion }}
kind: {{ $kind }}
metadata: {{ include "mariadb-manifests.metadata" $localvalues | nindent 2 }}
spec: {{ include "mariadb-manifests.spec" $localvalues | nindent 2 }}
{{- end }}
{{- end }}
