{{- if .Capabilities.APIVersions.Has "secret/v1" }}
{{- if .Values.secret -}}
apiVersion: v1
kind: Secret

metadata:
  {{- with .Values.secret.metadata }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

spec:
  {{- with .Values.secret.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
