name: Lint and Test Charts

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']

  push:
    branches: ['main']
    tags: ['v*']

env:
  CHART_PATH: charts

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.3.1
        with:
          command: lint
          config: .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Runs helm-docs
        run: bash .github/helm-docs.sh

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.19.0
          - v1.21.3
          - v1.23.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: bash .github/kubeval.sh
        
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
      - kubeval-chart
    strategy:
      matrix:
        k8s:
          - v1.19.0
          - v1.21.3
          - v1.23.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.4.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v2.3.1
        with:
          command: install
          config: .github/ct.yaml
