name: Lint and Test Charts

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']

  push:
    branches: ['main']
    tags: ['v*']

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      # - name: Run chart-testing (list-changed)
      #   id: list-changed
      #   run: |
      #     changed=$(ct list-changed --target-branch "${{ github.event.repository.default_branch }}")
      #     if [[ -n "$changed" ]]; then
      #       echo "::set-output name=changed::true"
      #     fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Generate manifests
        run: |
          mkdir -p "manifests"
          for CHART in $(ls -d charts/*/); do
            helm template "${CHART}" --generate-name --output-dir "manifests"
          done

      - name: Check kube-score
        uses: piraces/kube-score-ga@v0.1.3
        with:
          manifests-folders: manifests/**/*.yaml
          ignore-exit-code: true

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Lint helm docs
        run: bash .github/helm-docs.sh
