apiVersion: v1
kind: Service
metadata:
  name: {{ include "soft-serve.fullname" . }}-headless
  labels:
    {{- include "soft-serve.labels" . | nindent 4 }}
spec:
  clusterIP: None  # Headless service
  ports:
    - name: ssh
      port: {{ .Values.service.port }}
      protocol: TCP
  selector: {{ include "soft-serve.selectorLabels" . | nindent 4 }}
